import { useEffect, useState } from 'react';
import { CalendarDays, Download, Filter, RefreshCw } from 'lucide-react';
import api from '../lib/api';

const today = () => new Date().toISOString().split('T')[0];
function HistoryPage() {
  const [range, setRange] = useState({ fromdate: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString().split('T')[0], todate: today() });
  const [sales, setSales] = useState([]);
  const [state, setState] = useState({ loading: true, error: '' });
  const load = async () => { setState({ loading: true, error: '' }); try { const response = await api.post('/franchise/fetchSales', { fromdate: range.fromdate, todate: `${range.todate}T23:59:59.999Z` }); setSales(response.data.appdata || []); } catch (error) { setState({ loading: false, error: error.response?.data?.msg || 'Unable to load sales history.' }); } finally { setState((current) => ({ ...current, loading: false })); } };
  // The initial query intentionally uses the initial date window.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load(); }, []);
  const download = () => { const content = [['Date', 'Amount'], ...sales.map((sale) => [new Date(sale.date).toLocaleDateString(), sale.amount])].map((row) => row.join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type: 'text/csv' })); link.download = `sales-${range.fromdate}-${range.todate}.csv`; link.click(); URL.revokeObjectURL(link.href); };
  const total = sales.reduce((sum, sale) => sum + Number(sale.amount || 0), 0);
  return <section><div className="mb-7"><p className="text-sm text-[#718078]">Review and export your records</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">Sales history</h2></div><div className="mb-5 rounded-xl border border-[#dce2dc] bg-[#fbfcf9] p-5"><form onSubmit={(event) => { event.preventDefault(); load(); }} className="flex flex-wrap items-end gap-4"><label className="text-sm font-medium text-[#35554a]">From<input type="date" value={range.fromdate} max={range.todate} onChange={(event) => setRange({ ...range, fromdate: event.target.value })} className="mt-2 block rounded-lg border border-[#ccd7d0] bg-white px-3 py-2.5" /></label><label className="text-sm font-medium text-[#35554a]">To<input type="date" value={range.todate} min={range.fromdate} max={today()} onChange={(event) => setRange({ ...range, todate: event.target.value })} className="mt-2 block rounded-lg border border-[#ccd7d0] bg-white px-3 py-2.5" /></label><button disabled={state.loading} className="flex items-center gap-2 rounded-lg bg-[#356b59] px-4 py-2.5 text-sm font-semibold text-white"><Filter size={16} />{state.loading ? 'Loading...' : 'Filter'}</button><button type="button" disabled={!sales.length} onClick={download} className="flex items-center gap-2 rounded-lg border border-[#9bb6a7] px-4 py-2.5 text-sm font-semibold text-[#356b59] disabled:opacity-50"><Download size={16} />Export CSV</button></form></div>{state.error && <p className="mb-5 rounded-lg bg-[#fff3f1] p-4 text-sm text-[#9a3f3b]">{state.error}</p>}<div className="mb-4 flex items-center justify-between text-sm text-[#718078]"><span>{sales.length} records</span><strong className="text-[#35554a]">Total ₹{total.toLocaleString()}</strong></div><div className="overflow-hidden rounded-xl border border-[#dce2dc] bg-[#fbfcf9]">{state.loading ? <div className="flex h-48 items-center justify-center text-[#718078]"><RefreshCw className="animate-spin" /></div> : sales.length ? <table className="w-full text-left text-sm"><thead className="border-b border-[#dce2dc] text-xs uppercase tracking-wider text-[#718078]"><tr><th className="px-5 py-4">Date</th><th className="px-5 py-4 text-right">Amount</th></tr></thead><tbody className="divide-y divide-[#e5e9e5]">{sales.map((sale) => <tr key={sale._id}><td className="px-5 py-4 text-[#718078]"><CalendarDays className="mr-2 inline" size={15} />{new Date(sale.date).toLocaleDateString()}</td><td className="px-5 py-4 text-right font-semibold text-[#35554a]">₹{Number(sale.amount).toLocaleString()}</td></tr>)}</tbody></table> : <p className="p-12 text-center text-sm text-[#718078]">No sales recorded for this period.</p>}</div></section>;
}
export default HistoryPage;
